version: '3'

services:
  fastapi:
    build: .
    ports:
      - "80:8000"
    container_name: fastapi_fftt
    links:
      - redis:redis
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "8001:8001"
    environment:
      - REDISINSIGHT_HOSTS=redis:6379